### PR TITLE
Starling Fix

### PR DESCRIPTION
**Pull request by Doppp**
This is for #244. I didn't/haven't added a check for meshes in `rendering/BatchProcesser.hx` because I don't think you use `BatchPricessor.hx` so far (I prefer to add features only when necessary hehe). Feel free to change the folder names and reorganize the code better for potential future extensions of `Starling`.

Do you think we should have documentation for Starling Shapes?

Please review before merging. I hope I didn't break anything! 🙏 🙏 🙏

### CODE REVIEW

**Comment by TerryCavanagh** [comment]
Hey! This is pretty great, thank you for your work :D It looks solid!

So, @mrcdk has just started work on Dicey Dungeons, and this has already meant a few pull requests to fix various bugs with starling. Given that haxegon's local version of starling is likely to be changing a lot faster than the haxelib version of starling in the coming days and weeks, I think I'm going to leave starling in the live version of the library - at least until things settle down.

I do want to merge your changes wtih `HaxegonRenderTexture` and the startling shapes change, though! Really great to have that done, thank you!

**Comment by Doppp** [comment]
Sure! The changes here were not that much tbh. Maybe @mrcdk can take a look and see if the local version of starling hasn't changed much and it's still possible to merge these in. My worry is that if too much work gets done on the current version, trying to extract things out like this PR will be even more tedious. Better to nip it in the first and do extended classes like `HaxegonRenderTexture` rather than working directly on the library.

**Comment by TerryCavanagh** [comment]
Hey! Applied this to master :)

Don't think I want to mess around with a separate haxegon-starling right now, I think this will all settle down soon enough. Thanks!

**Comment by Doppp** [comment]
Cheers, @TerryCavanagh! Thanks! :+1:

**Pull request closed without merging**
